name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.3', '8.4']
        symfony_version: ['6.4.*', '7.0.*']

    name: PHP ${{ matrix.php }} Symfony ${{ matrix.symfony_version }}

    steps:
      - uses: actions/checkout@v4

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ matrix.php }}-${{ matrix.symfony_version }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-${{ matrix.php }}-${{ matrix.symfony_version }}-

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: :xdebug

      - run: php ./tests/bin/pin-symfony-version.php "${{ matrix.symfony_version }}"

      - run: composer update --no-progress

      - run: ./vendor/bin/phpcs
      - run: ./vendor/bin/psalm
      - run: ./vendor/bin/phpunit
