name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.3', '8.4']
        symfony_version: ['5.4.*', '6.4.*', '7.0.*']

    name: PHP ${{ matrix.php }} Symfony ${{ matrix.symfony_version }}

    services:
      rabbitmq:
        image: rabbitmq:4.0
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672

    steps:
      - uses: actions/checkout@v4

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ matrix.php }}-${{ matrix.symfony_version }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-${{ matrix.php }}-${{ matrix.symfony_version }}-

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: :xdebug

      - run: php ./tests/bin/pin-symfony-version.php "${{ matrix.symfony_version }}"

      - run: composer update --no-progress

      - name: PHPCS
        run: ./vendor/bin/phpcs

      - name: Psalm
        run: ./vendor/bin/psalm

      - name: PHPUnit
        run: ./vendor/bin/phpunit
        env:
          MESSENGER_TRANSPORT_PHPAMQPLIB_DSN: "phpamqplib://guest:guest@127.0.0.1:${{ job.services.rabbitmq.ports['5672'] }}/%2f/messages"
